# Generated by Django 6.0 on 2025-12-18 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0002_streamplatform_watchlist_delete_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='atoryline',
            new_name='storyline',
        ),
    ]
